# -*- coding: utf-8 -*-
"""task-3: Object Detection (Basic)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J6h0kL-fxgmGCXHxK1xwMWryuNjaU27R
"""

import cv2
from matplotlib import pyplot as plt


# Opening image
img = cv2.imread("/content/donaldsnephews.jpg")

# OpenCV opens images as BRG
# but we want it as RGB and
# we also need a grayscale
# version
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Creates the environment
# of the picture and shows it
plt.subplot(1, 1, 1)
plt.imshow(img_rgb)
plt.show()